workflows:

  flutter-ios-simulator:

    name: Flutter iOS Simulator

    environment:

      flutter: 3.35.0

      xcode: 16.2

    scripts:
      - flutter build ios --simulator

    artifacts:

      - build/ios/iphonesimulator/Runner.app