// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyo2-xXzjTt_AQwEg_RMrdV2lvnpih7GE',
    appId: '1:588085741239:web:df30259a0bdc1f1d5c2f32',
    messagingSenderId: '588085741239',
    projectId: 'chorezilla-dev',
    authDomain: 'chorezilla-dev.firebaseapp.com',
    storageBucket: 'chorezilla-dev.firebasestorage.app',
    measurementId: 'G-GNQ583NFSG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfGQwOTXJsS2AW6sj2jv3_KIEL6TKIgfI',
    appId: '1:588085741239:android:7915b00b78dba9f25c2f32',
    messagingSenderId: '588085741239',
    projectId: 'chorezilla-dev',
    storageBucket: 'chorezilla-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGUy66KMo_BXdTzUKG3ImVsODmtE7Quuw',
    appId: '1:588085741239:ios:e6ecbf97dc9eddb25c2f32',
    messagingSenderId: '588085741239',
    projectId: 'chorezilla-dev',
    storageBucket: 'chorezilla-dev.firebasestorage.app',
    iosClientId: '588085741239-auq29s1kutqjjto23re395l76m8t1o9a.apps.googleusercontent.com',
    iosBundleId: 'com.chorezilla.chorezilla',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGUy66KMo_BXdTzUKG3ImVsODmtE7Quuw',
    appId: '1:588085741239:ios:e6ecbf97dc9eddb25c2f32',
    messagingSenderId: '588085741239',
    projectId: 'chorezilla-dev',
    storageBucket: 'chorezilla-dev.firebasestorage.app',
    iosClientId: '588085741239-auq29s1kutqjjto23re395l76m8t1o9a.apps.googleusercontent.com',
    iosBundleId: 'com.chorezilla.chorezilla',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyo2-xXzjTt_AQwEg_RMrdV2lvnpih7GE',
    appId: '1:588085741239:web:9b9511d8893e71335c2f32',
    messagingSenderId: '588085741239',
    projectId: 'chorezilla-dev',
    authDomain: 'chorezilla-dev.firebaseapp.com',
    storageBucket: 'chorezilla-dev.firebasestorage.app',
    measurementId: 'G-M3F1L8T5HR',
  );
}
